// <auto-generated />
using System;
using FdkElevator.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FdkElevator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528184417_added_order1")]
    partial class added_order1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FdkElevator.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FirstTimeLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PasswordResetExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Building_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<int>("NumberofElevators")
                        .HasColumnType("int");

                    b.Property<int>("NumberofFloors")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForLoss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SalesPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("clientCategory")
                        .HasColumnType("int");

                    b.Property<string>("decisionMaker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("leadStatus")
                        .HasColumnType("int");

                    b.Property<int>("leadType")
                        .HasColumnType("int");

                    b.Property<int>("source")
                        .HasColumnType("int");

                    b.Property<int>("urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesPersonId");

                    b.HasIndex("TenantId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("FdkElevator.Models.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FdkElevator.Models.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FdkElevator.Models.Orders.ShippingAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("ShippingAddresses");
                });

            modelBuilder.Entity("FdkElevator.Models.Organization.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BasicPlanCost")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("FreePlanCost")
                        .HasColumnType("real");

                    b.Property<float>("PremiumPlanCost")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("projectTasks");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.ProjectTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("projectTeams");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.LiftConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CabinFinish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiftType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stops")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId")
                        .IsUnique();

                    b.HasIndex("RevisionId");

                    b.ToTable("liftConfigurations");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.LiftConfigurationRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CabinFinish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiftType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stops")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId")
                        .IsUnique();

                    b.ToTable("liftConfigurationsRevision");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AmcOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CustomsCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<decimal>("FreightCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InstallationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuotationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<decimal>("SubcontractorCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("int");

                    b.Property<string>("Warranty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuotationPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("QuotationId");

                    b.HasIndex("RevisionId");

                    b.ToTable("quotationPayments");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuoteItems");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItemRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("revisionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("revisionId");

                    b.ToTable("quoteItemRevisions");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Revision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AmcOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CustomsCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<decimal>("FreightCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InstallationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevisionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<decimal>("SubcontractorCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("int");

                    b.Property<string>("Warranty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LeadId");

                    b.HasIndex("QuotationId");

                    b.ToTable("revisions");
                });

            modelBuilder.Entity("FdkElevator.Models.Selection.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SelectedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupplierItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SelectedProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FdkElevator.Models.Selection.SelectedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("approvedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isApproved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("approvedBy");

                    b.ToTable("SelectedProducts");
                });

            modelBuilder.Entity("FdkElevator.Models.Suppliers.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PasswordResetExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("FdkElevator.Models.Suppliers.SupplierItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplierItems");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.AdditionalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteChallenges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurveyorRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("AdditionalNotes");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.AllSurvey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SurveyorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.HasIndex("SurveyorId");

                    b.HasIndex("TenantId");

                    b.ToTable("AllSurveys");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.EntranceDoor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DoorOpeningType")
                        .HasColumnType("int");

                    b.Property<string>("DoorSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandingDoorFinishPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfEntrances")
                        .HasColumnType("int");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("EntranceDoorDetails");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.FinishingDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CabinFinishPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeilingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayTypePreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlooringPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HandrailsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("MirrorRequired")
                        .HasColumnType("bit");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("FinishingDesignPreferences");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.MaintenanceService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentLiftCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExistingLiftOnSite")
                        .HasColumnType("bit");

                    b.Property<bool>("MaintenanceContractRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceFrequencyPreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("MaintenanceServiceInfos");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.PowerElectrical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BackupGeneratorAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("DedicatedLiftPowerLineAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("PowerSupplyAvailable")
                        .HasColumnType("int");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoltageAvailable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("PowerElectricalInfos");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.ProjectInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstimatedCompletionTimeline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiftTypeRequired")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLiftsRequired")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStopsFloors")
                        .HasColumnType("int");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TravelHeightMeters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("projectInfos");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.SafetyCompliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AccessControlRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("CctvRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ComplianceStandardRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmergencyRescueSystemRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("FiremanOperationRequired")
                        .HasColumnType("bit");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("SafetyComplianceInfos");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.ShaftStructural", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CivilWorksRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("CoreCuttingRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("MachineRoomAvailability")
                        .HasColumnType("bit");

                    b.Property<string>("MachineRoomLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverheadHeightHeadroom")
                        .HasColumnType("float");

                    b.Property<double>("PitDepth")
                        .HasColumnType("float");

                    b.Property<double>("ShaftHeight")
                        .HasColumnType("float");

                    b.Property<int>("ShaftLocation")
                        .HasColumnType("int");

                    b.Property<string>("ShaftSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShaftType")
                        .HasColumnType("int");

                    b.Property<bool>("StructuralDrawingsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("ShaftStructuralInfos");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.SiteMediaAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("SiteAttachments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("SiteMediaAttachments");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.UsageTraffic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessibilityRequirements")
                        .HasColumnType("int");

                    b.Property<int>("BuildingUsage")
                        .HasColumnType("int");

                    b.Property<string>("EstimatedDailyTraffic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeakUsageHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("UsageTrafficInfos");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscriptionExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Subscription_Plan")
                        .HasColumnType("int");

                    b.Property<int?>("Subscription_Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.TenantSub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripePaymentIntent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSubs");
                });

            modelBuilder.Entity("FdkElevator.Models.Auth.User", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "ten")
                        .WithMany("users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ten");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Activity", b =>
                {
                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithMany("activities")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "Tenant")
                        .WithMany("activities")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Auth.User", "user")
                        .WithMany("activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Tenant");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Lead", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithMany("leads")
                        .HasForeignKey("SalesPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FdkElevator.Models.Orders.Order", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "Tenant")
                        .WithMany("orders")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FdkElevator.Models.Orders.OrderItem", b =>
                {
                    b.HasOne("FdkElevator.Models.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FdkElevator.Models.Orders.ShippingAddress", b =>
                {
                    b.HasOne("FdkElevator.Models.Orders.Order", "Order")
                        .WithOne("ShippingAddress")
                        .HasForeignKey("FdkElevator.Models.Orders.ShippingAddress", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.Material", b =>
                {
                    b.HasOne("FdkElevator.Models.Projects.Project", "Project")
                        .WithMany("Materials")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.Project", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "user")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.ProjectTask", b =>
                {
                    b.HasOne("FdkElevator.Models.Projects.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.ProjectTeam", b =>
                {
                    b.HasOne("FdkElevator.Models.Projects.Project", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Auth.User", "user")
                        .WithMany("users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.LiftConfiguration", b =>
                {
                    b.HasOne("FdkElevator.Models.Quotations.Quotation", "quotation")
                        .WithOne("configuration")
                        .HasForeignKey("FdkElevator.Models.Quotations.LiftConfiguration", "QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Quotations.Revision", "revision")
                        .WithMany()
                        .HasForeignKey("RevisionId");

                    b.Navigation("quotation");

                    b.Navigation("revision");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.LiftConfigurationRevision", b =>
                {
                    b.HasOne("FdkElevator.Models.Quotations.Revision", "revision")
                        .WithOne("configuration")
                        .HasForeignKey("FdkElevator.Models.Quotations.LiftConfigurationRevision", "RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("revision");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Quotation", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithMany("quotations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithOne("quotation")
                        .HasForeignKey("FdkElevator.Models.Quotations.Quotation", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuotationPayment", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "user")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Quotations.Quotation", "quotation")
                        .WithMany("Payment")
                        .HasForeignKey("QuotationId");

                    b.HasOne("FdkElevator.Models.Quotations.Revision", "revision")
                        .WithMany("Payment")
                        .HasForeignKey("RevisionId");

                    b.Navigation("quotation");

                    b.Navigation("revision");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItem", b =>
                {
                    b.HasOne("FdkElevator.Models.Quotations.Quotation", "Quotation")
                        .WithMany("Items")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItemRevision", b =>
                {
                    b.HasOne("FdkElevator.Models.Quotations.Revision", "revision")
                        .WithMany("Items")
                        .HasForeignKey("revisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("revision");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Revision", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Quotations.Quotation", "Quotation")
                        .WithMany("revisions")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Quotation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FdkElevator.Models.Selection.Product", b =>
                {
                    b.HasOne("FdkElevator.Models.Selection.SelectedProduct", null)
                        .WithMany("Products")
                        .HasForeignKey("SelectedProductId");
                });

            modelBuilder.Entity("FdkElevator.Models.Selection.SelectedProduct", b =>
                {
                    b.HasOne("FdkElevator.Models.Projects.Project", "Project")
                        .WithOne("SelectedProduct")
                        .HasForeignKey("FdkElevator.Models.Selection.SelectedProduct", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Auth.User", "user")
                        .WithMany("selectedProducts")
                        .HasForeignKey("approvedBy");

                    b.Navigation("Project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FdkElevator.Models.Suppliers.SupplierItem", b =>
                {
                    b.HasOne("FdkElevator.Models.Suppliers.Supplier", "Supplier")
                        .WithMany("Suppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.AdditionalNote", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("AdditionalNotes")
                        .HasForeignKey("FdkElevator.Models.Surveyors.AdditionalNote", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.AllSurvey", b =>
                {
                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithOne("survey")
                        .HasForeignKey("FdkElevator.Models.Surveyors.AllSurvey", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithMany("surveyors")
                        .HasForeignKey("SurveyorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "tenant")
                        .WithMany("surveys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("User");

                    b.Navigation("tenant");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.EntranceDoor", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("EntranceDoorDetails")
                        .HasForeignKey("FdkElevator.Models.Surveyors.EntranceDoor", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.FinishingDesign", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("FinishingDesignPreferences")
                        .HasForeignKey("FdkElevator.Models.Surveyors.FinishingDesign", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.MaintenanceService", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("MaintenanceServiceInfo")
                        .HasForeignKey("FdkElevator.Models.Surveyors.MaintenanceService", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.PowerElectrical", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("PowerElectricalInfo")
                        .HasForeignKey("FdkElevator.Models.Surveyors.PowerElectrical", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.ProjectInfo", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("ProjectInfo")
                        .HasForeignKey("FdkElevator.Models.Surveyors.ProjectInfo", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.SafetyCompliance", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("SafetyComplianceInfo")
                        .HasForeignKey("FdkElevator.Models.Surveyors.SafetyCompliance", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.ShaftStructural", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("ShaftStructuralInfo")
                        .HasForeignKey("FdkElevator.Models.Surveyors.ShaftStructural", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.SiteMediaAttachment", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("SiteMediaAttachments")
                        .HasForeignKey("FdkElevator.Models.Surveyors.SiteMediaAttachment", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.UsageTraffic", b =>
                {
                    b.HasOne("FdkElevator.Models.Surveyors.AllSurvey", "Survey")
                        .WithOne("UsageTrafficInfo")
                        .HasForeignKey("FdkElevator.Models.Surveyors.UsageTraffic", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.Tenant", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", null)
                        .WithMany("tenants")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.TenantSub", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "Tenant")
                        .WithOne("TenantSub")
                        .HasForeignKey("FdkElevator.Models.Tenants.TenantSub", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FdkElevator.Models.Auth.User", b =>
                {
                    b.Navigation("activities");

                    b.Navigation("leads");

                    b.Navigation("quotations");

                    b.Navigation("selectedProducts");

                    b.Navigation("surveyors");

                    b.Navigation("users");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Lead", b =>
                {
                    b.Navigation("activities");

                    b.Navigation("quotation")
                        .IsRequired();

                    b.Navigation("survey")
                        .IsRequired();
                });

            modelBuilder.Entity("FdkElevator.Models.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.Project", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("SelectedProduct")
                        .IsRequired();

                    b.Navigation("Tasks");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Quotation", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");

                    b.Navigation("configuration")
                        .IsRequired();

                    b.Navigation("revisions");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Revision", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");

                    b.Navigation("configuration")
                        .IsRequired();
                });

            modelBuilder.Entity("FdkElevator.Models.Selection.SelectedProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FdkElevator.Models.Suppliers.Supplier", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.AllSurvey", b =>
                {
                    b.Navigation("AdditionalNotes")
                        .IsRequired();

                    b.Navigation("EntranceDoorDetails")
                        .IsRequired();

                    b.Navigation("FinishingDesignPreferences")
                        .IsRequired();

                    b.Navigation("MaintenanceServiceInfo")
                        .IsRequired();

                    b.Navigation("PowerElectricalInfo")
                        .IsRequired();

                    b.Navigation("ProjectInfo")
                        .IsRequired();

                    b.Navigation("SafetyComplianceInfo")
                        .IsRequired();

                    b.Navigation("ShaftStructuralInfo")
                        .IsRequired();

                    b.Navigation("SiteMediaAttachments")
                        .IsRequired();

                    b.Navigation("UsageTrafficInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.Tenant", b =>
                {
                    b.Navigation("TenantSub")
                        .IsRequired();

                    b.Navigation("activities");

                    b.Navigation("orders");

                    b.Navigation("surveys");

                    b.Navigation("tenants");

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
