// <auto-generated />
using System;
using FdkElevator.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FdkElevator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521101050_surveyor_notes")]
    partial class surveyor_notes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FdkElevator.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FirstTimeLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PasswordResetExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Building_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<int>("NumberofElevators")
                        .HasColumnType("int");

                    b.Property<int>("NumberofFloors")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SalesPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("clientCategory")
                        .HasColumnType("int");

                    b.Property<int>("leadStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesPersonId");

                    b.HasIndex("TenantId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("FdkElevator.Models.Organization.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BasicPlanCost")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("FreePlanCost")
                        .HasColumnType("real");

                    b.Property<float>("PremiumPlanCost")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuoteItems");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CivicReady")
                        .HasColumnType("bit");

                    b.Property<string>("CivicWorkRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EngineerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("MLROption")
                        .HasColumnType("bit");

                    b.Property<bool?>("MachineRoom")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OverheadClearance")
                        .HasColumnType("int");

                    b.Property<int?>("PitDepth")
                        .HasColumnType("int");

                    b.Property<string>("PowerSupply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendedLift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafetyRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShaftAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("ShaftDepth")
                        .HasColumnType("int");

                    b.Property<int?>("ShaftWidth")
                        .HasColumnType("int");

                    b.Property<string>("StorageArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("numberofStops")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.HasIndex("SurveyorId");

                    b.HasIndex("TenantId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscriptionExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Subscription_Plan")
                        .HasColumnType("int");

                    b.Property<int?>("Subscription_Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.TenantSub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripePaymentIntent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSubs");
                });

            modelBuilder.Entity("FdkElevator.Models.Auth.User", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "ten")
                        .WithMany("users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ten");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Lead", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithMany("leads")
                        .HasForeignKey("SalesPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Quotation", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithOne("Quotation")
                        .HasForeignKey("FdkElevator.Models.Quotations.Quotation", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithOne("quotation")
                        .HasForeignKey("FdkElevator.Models.Quotations.Quotation", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItem", b =>
                {
                    b.HasOne("FdkElevator.Models.Quotations.Quotation", "Quotation")
                        .WithMany("Items")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.Survey", b =>
                {
                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithOne("survey")
                        .HasForeignKey("FdkElevator.Models.Surveyors.Survey", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithMany("surveyors")
                        .HasForeignKey("SurveyorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "tenant")
                        .WithMany("surveys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("User");

                    b.Navigation("tenant");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.Tenant", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", null)
                        .WithMany("tenants")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.TenantSub", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "Tenant")
                        .WithOne("TenantSub")
                        .HasForeignKey("FdkElevator.Models.Tenants.TenantSub", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FdkElevator.Models.Auth.User", b =>
                {
                    b.Navigation("Quotation")
                        .IsRequired();

                    b.Navigation("leads");

                    b.Navigation("surveyors");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Lead", b =>
                {
                    b.Navigation("quotation")
                        .IsRequired();

                    b.Navigation("survey")
                        .IsRequired();
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Quotation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.Tenant", b =>
                {
                    b.Navigation("TenantSub")
                        .IsRequired();

                    b.Navigation("surveys");

                    b.Navigation("tenants");

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
