// <auto-generated />
using System;
using FdkElevator.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FdkElevator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525050634_projects_retake")]
    partial class projects_retake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FdkElevator.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FirstTimeLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PasswordResetExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Building_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<int>("NumberofElevators")
                        .HasColumnType("int");

                    b.Property<int>("NumberofFloors")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForLoss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SalesPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("clientCategory")
                        .HasColumnType("int");

                    b.Property<string>("decisionMaker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("leadStatus")
                        .HasColumnType("int");

                    b.Property<int>("leadType")
                        .HasColumnType("int");

                    b.Property<int>("source")
                        .HasColumnType("int");

                    b.Property<int>("urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesPersonId");

                    b.HasIndex("TenantId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("FdkElevator.Models.Organization.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BasicPlanCost")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("FreePlanCost")
                        .HasColumnType("real");

                    b.Property<float>("PremiumPlanCost")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("projectTasks");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.ProjectTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("projectTeams");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.LiftConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CabinFinish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiftType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stops")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId")
                        .IsUnique();

                    b.HasIndex("RevisionId");

                    b.ToTable("liftConfigurations");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.LiftConfigurationRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CabinFinish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiftType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stops")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId")
                        .IsUnique();

                    b.ToTable("liftConfigurationsRevision");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AmcOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CustomsCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<decimal>("FreightCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InstallationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuotationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<decimal>("SubcontractorCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("int");

                    b.Property<string>("Warranty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuotationPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("QuotationId");

                    b.HasIndex("RevisionId");

                    b.ToTable("quotationPayments");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuoteItems");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItemRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("revisionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("revisionId");

                    b.ToTable("quoteItemRevisions");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Revision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AmcOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CustomsCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<decimal>("FreightCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InstallationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevisionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<decimal>("SubcontractorCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("int");

                    b.Property<string>("Warranty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LeadId");

                    b.HasIndex("QuotationId");

                    b.ToTable("revisions");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CivicReady")
                        .HasColumnType("bit");

                    b.Property<string>("CivicWorkRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EngineerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("MLROption")
                        .HasColumnType("bit");

                    b.Property<bool?>("MachineRoom")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OverheadClearance")
                        .HasColumnType("int");

                    b.Property<int?>("PitDepth")
                        .HasColumnType("int");

                    b.Property<string>("PowerSupply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendedLift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafetyRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShaftAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("ShaftDepth")
                        .HasColumnType("int");

                    b.Property<int?>("ShaftWidth")
                        .HasColumnType("int");

                    b.Property<string>("StorageArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("numberofStops")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.HasIndex("SurveyorId");

                    b.HasIndex("TenantId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscriptionExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Subscription_Plan")
                        .HasColumnType("int");

                    b.Property<int?>("Subscription_Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.TenantSub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripePaymentIntent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSubs");
                });

            modelBuilder.Entity("FdkElevator.Models.Auth.User", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "ten")
                        .WithMany("users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ten");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Activity", b =>
                {
                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithMany("activities")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "Tenant")
                        .WithMany("activities")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Auth.User", "user")
                        .WithMany("activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Tenant");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Lead", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithMany("leads")
                        .HasForeignKey("SalesPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.Project", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "user")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.ProjectTask", b =>
                {
                    b.HasOne("FdkElevator.Models.Projects.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.ProjectTeam", b =>
                {
                    b.HasOne("FdkElevator.Models.Projects.Project", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Auth.User", "user")
                        .WithMany("users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.LiftConfiguration", b =>
                {
                    b.HasOne("FdkElevator.Models.Quotations.Quotation", "quotation")
                        .WithOne("configuration")
                        .HasForeignKey("FdkElevator.Models.Quotations.LiftConfiguration", "QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Quotations.Revision", "revision")
                        .WithMany()
                        .HasForeignKey("RevisionId");

                    b.Navigation("quotation");

                    b.Navigation("revision");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.LiftConfigurationRevision", b =>
                {
                    b.HasOne("FdkElevator.Models.Quotations.Revision", "revision")
                        .WithOne("configuration")
                        .HasForeignKey("FdkElevator.Models.Quotations.LiftConfigurationRevision", "RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("revision");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Quotation", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithOne("Quotation")
                        .HasForeignKey("FdkElevator.Models.Quotations.Quotation", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithOne("quotation")
                        .HasForeignKey("FdkElevator.Models.Quotations.Quotation", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuotationPayment", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "user")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Quotations.Quotation", "quotation")
                        .WithMany("Payment")
                        .HasForeignKey("QuotationId");

                    b.HasOne("FdkElevator.Models.Quotations.Revision", "revision")
                        .WithMany("Payment")
                        .HasForeignKey("RevisionId");

                    b.Navigation("quotation");

                    b.Navigation("revision");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItem", b =>
                {
                    b.HasOne("FdkElevator.Models.Quotations.Quotation", "Quotation")
                        .WithMany("Items")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.QuoteItemRevision", b =>
                {
                    b.HasOne("FdkElevator.Models.Quotations.Revision", "revision")
                        .WithMany("Items")
                        .HasForeignKey("revisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("revision");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Revision", b =>
                {
                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Quotations.Quotation", "Quotation")
                        .WithMany("revisions")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Quotation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FdkElevator.Models.Surveyors.Survey", b =>
                {
                    b.HasOne("FdkElevator.Models.Leads.Lead", "Lead")
                        .WithOne("survey")
                        .HasForeignKey("FdkElevator.Models.Surveyors.Survey", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Auth.User", "User")
                        .WithMany("surveyors")
                        .HasForeignKey("SurveyorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "tenant")
                        .WithMany("surveys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("User");

                    b.Navigation("tenant");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.Tenant", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", null)
                        .WithMany("tenants")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.TenantSub", b =>
                {
                    b.HasOne("FdkElevator.Models.Tenants.Tenant", "Tenant")
                        .WithOne("TenantSub")
                        .HasForeignKey("FdkElevator.Models.Tenants.TenantSub", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FdkElevator.Models.Auth.User", b =>
                {
                    b.Navigation("Quotation")
                        .IsRequired();

                    b.Navigation("activities");

                    b.Navigation("leads");

                    b.Navigation("surveyors");

                    b.Navigation("users");
                });

            modelBuilder.Entity("FdkElevator.Models.Leads.Lead", b =>
                {
                    b.Navigation("activities");

                    b.Navigation("quotation")
                        .IsRequired();

                    b.Navigation("survey")
                        .IsRequired();
                });

            modelBuilder.Entity("FdkElevator.Models.Projects.Project", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Quotation", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");

                    b.Navigation("configuration")
                        .IsRequired();

                    b.Navigation("revisions");
                });

            modelBuilder.Entity("FdkElevator.Models.Quotations.Revision", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");

                    b.Navigation("configuration")
                        .IsRequired();
                });

            modelBuilder.Entity("FdkElevator.Models.Tenants.Tenant", b =>
                {
                    b.Navigation("TenantSub")
                        .IsRequired();

                    b.Navigation("activities");

                    b.Navigation("surveys");

                    b.Navigation("tenants");

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
